### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by peckpeck** [lastops/sublime-cfengine3#7]
Hello,

I would love to have a cfengine syntax on github. An the syntax you are using for sublime text is accepted by github for their highlighter.
However, they need a proper license before we can submit it. 
Can you give an opensource license to this project ?

Thank you,
peckpeck

**Comment by vastrave** [comment]
Hello, Sorry for the delay. I publish it under GPLv3 https://github.com/lastops/sublime-cfengine3/blob/master/LICENSE. Feel free to publish it. Thank you!
